### ISSUE TITLE
Should not this be just `br`?

### ISSUE THREAD

**Issue by Bobris** [Xrew/remark-bobril#1]
https://github.com/Xrew/remark-bobril/blob/300a216d3cc5cd16d5a0d73c656d6aa724768ec4/src/components/break/lib.ts#L9

**Comment by Xrew** [comment]
Yes, sure. The directory of component was named **br**. After I have renamed it to **break**, my editor was so 'clever' and remane the value of 'tag' too :)
Thank you.

**Comment by Xrew** [comment]
Fixed in Fixed in 6fcfe8802354fd3b52f5315a985cab3a57d332cd
